### PR TITLE
Postgresql binding bug

### LINKED ISSUE #163: PostgreSQL improper values for bindings
```
12:43:34 PM - debug:  error: insert into "annotation" ("annotation_format", "annotation_id", "locus_id", "locus_symbol_id", "publication_id", "status_id", "submission_id", "submitter_id", "type_id") values ($1, $2, $3, $4, $5, $6, $7, $8, $9) returning "id" - invalid input syntax for integer: "comment_annotation"
    at Connection.parseE (/home/ec2-user/deployments/toastdos-back/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/home/ec2-user/deployments/toastdos-back/node_modules/pg/lib/connection.js:396:17)
    at Socket.<anonymous> (/home/ec2-user/deployments/toastdos-back/node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```
We are getting this error on submission in production. Investigate and fix this issue.

### PR DESCRIPTION
**Pull request by Mimickal**
Closes #163

### CODE REVIEW

File: scripts/postgresql_setup.sh [hunk 1]
```diff
@@ -0,0 +1,36 @@
+#!/bin/bash
```
Comment (jcdesimp) [inline scripts/postgresql_setup.sh]: rename file to make clear that it is not for production.
