### PR TITLE
Graceful obo error

### LINKED ISSUE #105: Entire obo import fails on single record error
The obo import script should gracefully recover from errors. If there is, for example, a name conflict when inserting a record, that error should be logged, but the importer should continue on to the next term. Currently the whole thing just stops on the error.

To reproduce error attempt to import an obo file with two keywords with the same name (or same external id)

### PR DESCRIPTION
**Pull request by Mimickal**
Closes #105

### CODE REVIEW

File: test/lib/obo_importer_test.js [hunk 1]
```diff
@@ -92,6 +93,32 @@ describe('OBO Data Importer', function() {
...
+		const goodId = 'GO:0000002';
+		const oboData =
+			'default-namespace: default_keyword_type\n' +
+			'[Term]\n' +
+			'id: GO:0000001\n' +
+			'\n' +
+			'[Term]\n' +
+			'id: ' + goodId + '\n' +
+			'name: test keyword 2\n';
+		fs.writeFileSync(badOboName, oboData);
```
Comment (jcdesimp) [inline test/lib/obo_importer_test.js]: add comment for why this is a negative test case.
